/* CEOSkit — Enhancement Pack v1.0
   Toast · Sound · Signal Log · Trade Logger · Win Rate · Countdown */

function toast(msg,type,ms){type=type||'info';ms=ms||4000;var r=document.getElementById('_tr');if(!r){r=document.createElement('div');r.id='_tr';r.style.cssText='position:fixed;top:12px;left:50%;transform:translateX(-50%);z-index:99999;display:flex;flex-direction:column;gap:6px;pointer-events:none;width:min(92vw,340px)';document.body.appendChild(r);}var p={info:{b:'rgba(63,81,181,.95)',e:'#5c6bc0',i:'ℹ'},win:{b:'rgba(0,180,60,.95)',e:'#00c853',i:'✓'},loss:{b:'rgba(220,48,48,.95)',e:'#ff5252',i:'✗'},strong:{b:'rgba(0,200,83,.95)',e:'#00e676',i:'🏆'},warn:{b:'rgba(255,145,0,.93)',e:'#ff9800',i:'⚠'},offline:{b:'rgba(180,0,0,.95)',e:'#ff1744',i:'📡'}};var s=p[type]||p.info,t=document.createElement('div');t.style.cssText='background:'+s.b+';border:1px solid '+s.e+';border-radius:12px;padding:11px 15px;pointer-events:all;cursor:pointer;box-shadow:0 4px 20px rgba(0,0,0,.4);display:flex;align-items:center;gap:10px';t.innerHTML='<span style="font-size:1rem;flex-shrink:0">'+s.i+'</span><span style="font-size:12px;font-weight:700;color:#fff;line-height:1.4">'+msg+'</span>';t.onclick=function(){t.remove();};r.appendChild(t);setTimeout(function(){t.remove();},ms);}

var _aC=null;
function _au(){if(!_aC)try{_aC=new(window.AudioContext||window.webkitAudioContext)();}catch(e){}return _aC;}
function _bp(f,d,tp,v){try{var c=_au();if(!c)return;var o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.type=tp||'sine';o.frequency.value=f;g.gain.setValueAtTime(v||.2,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.start();o.stop(c.currentTime+d);}catch(e){}}
function sndStrong(){_bp(523,.07,'sine',.28);setTimeout(function(){_bp(659,.07,'sine',.28);},80);setTimeout(function(){_bp(784,.2,'sine',.28);},160);}
function sndWin(){_bp(600,.07,'sine',.22);setTimeout(function(){_bp(800,.14,'sine',.22);},75);}
function sndLoss(){_bp(220,.12,'sawtooth',.18);setTimeout(function(){_bp(160,.22,'sawtooth',.15);},130);}
function sndTick(){_bp(440,.035,'sine',.07);}
function _sndOk(){var b=document.getElementById('sound-btn');return!b||b.getAttribute('data-on')!=='0';}

var SIG_LOG=[],_lastSigKey=null;
var TRADE_LOG=JSON.parse(localStorage.getItem('se_trades')||'[]');

function _recSig(signal,conf,type,price){var k=signal+'|'+conf+'|'+type;if(k===_lastSigKey)return;_lastSigKey=k;SIG_LOG.unshift({id:Date.now(),time:new Date().toTimeString().slice(0,8),signal:signal,conf:conf,type:type,price:price,result:null});if(SIG_LOG.length>60)SIG_LOG.pop();_renderSig();if(conf==='STRONG'){if(_sndOk())sndStrong();toast('🏆 STRONG: '+signal+' — '+type,'strong',5500);}}

function _renderSig(){var el=document.getElementById('sig-entries');if(!el)return;if(!SIG_LOG.length){el.innerHTML='<div style="text-align:center;color:var(--muted);font-size:11px;padding:28px">No signals yet</div>';return;}el.innerHTML=SIG_LOG.map(function(s,i){var up=/RISE|EVEN|OVER|MATCH/i.test(s.signal),col=up?'#00c853':'#ef4444';var cc=s.conf==='STRONG'?'#00c853':s.conf==='MODERATE'?'#f59e0b':'#94a3b8';var rp=s.result?'<span style="font-size:9px;font-weight:900;padding:2px 8px;border-radius:6px;color:'+(s.result==='win'?'#00c853':'#ef4444')+';background:'+(s.result==='win'?'#00c85322':'#ef444422')+';border:1px solid '+(s.result==='win'?'#00c853':'#ef4444')+'">'+s.result.toUpperCase()+'</span>':'<span onclick="asgSig('+i+',\'win\')" style="cursor:pointer;font-size:9px;font-weight:900;padding:2px 8px;border-radius:6px;color:#00c853;background:#00c85318;border:1px solid #00c853;margin-right:4px">W</span><span onclick="asgSig('+i+',\'loss\')" style="cursor:pointer;font-size:9px;font-weight:900;padding:2px 8px;border-radius:6px;color:#ef4444;background:#ef444418;border:1px solid #ef4444">L</span>';return'<div style="padding:9px 0;border-bottom:1px solid #e2e8f018;display:flex;align-items:flex-start;gap:8px"><div style="width:7px;height:7px;border-radius:50%;background:'+col+';flex-shrink:0;margin-top:5px"></div><div style="flex:1;min-width:0"><div style="display:flex;align-items:center;gap:5px;flex-wrap:wrap"><span style="font-size:13px;font-weight:900;color:'+col+'">'+s.signal+'</span><span style="font-size:7px;font-weight:700;padding:1px 6px;border-radius:8px;color:'+cc+';background:'+cc+'18;border:1px solid '+cc+'">'+s.conf+'</span></div><div style="font-size:9px;color:var(--muted);margin-top:2px">'+s.time+' · '+s.type+(s.price?' · '+Number(s.price).toFixed(4):'')+' </div></div>'+rp+'</div>';}).join('');}

function asgSig(i,r){if(SIG_LOG[i]){SIG_LOG[i].result=r;TRADE_LOG.unshift({time:SIG_LOG[i].time,signal:SIG_LOG[i].signal,conf:SIG_LOG[i].conf,type:SIG_LOG[i].type,result:r});if(TRADE_LOG.length>200)TRADE_LOG.pop();localStorage.setItem('se_trades',JSON.stringify(TRADE_LOG.slice(0,200)));_updWR();_renderSig();}}
function openSigDrawer(){var el=document.getElementById('sig-drawer');if(el)el.style.display='flex';_renderSig();_updWR();}
function closeSigDrawer(){var el=document.getElementById('sig-drawer');if(el)el.style.display='none';}
function logTrade(r){var last=SIG_LOG[0];TRADE_LOG.unshift({time:new Date().toTimeString().slice(0,8),signal:last?last.signal:'manual',conf:last?last.conf:'—',type:last?last.type:'—',result:r});if(TRADE_LOG.length>200)TRADE_LOG.pop();localStorage.setItem('se_trades',JSON.stringify(TRADE_LOG.slice(0,200)));if(SIG_LOG[0]&&!SIG_LOG[0].result)SIG_LOG[0].result=r;_updWR();_renderSig();if(r==='win'){if(_sndOk())sndWin();toast('✓ WIN logged','win',3000);}else{if(_sndOk())sndLoss();toast('✗ LOSS logged','loss',3000);}}
function clearTrades(){TRADE_LOG.length=0;localStorage.setItem('se_trades','[]');_updWR();toast('Trade log cleared','info',2500);}
function _updWR(){var card=document.getElementById('wr-card');if(!card)return;if(!TRADE_LOG.length){card.style.display='none';return;}card.style.display='block';var w=TRADE_LOG.filter(function(t){return t.result==='win';}).length,tot=TRADE_LOG.length,pct=w/tot*100;var col=pct>=55?'#00c853':pct>=45?'#f59e0b':'#ef4444';var pEl=document.getElementById('wr-pct'),bEl=document.getElementById('wr-bar');if(pEl){pEl.textContent=pct.toFixed(1)+'%';pEl.style.color=col;}if(bEl){bEl.style.width=pct+'%';bEl.style.background=col;}var wE=document.getElementById('wr-w'),lE=document.getElementById('wr-l'),tE=document.getElementById('wr-t');if(wE)wE.textContent=w+' wins';if(lE)lE.textContent=(tot-w)+' losses';if(tE)tE.textContent=tot+' trades';}

var _ltTs=Date.now(),_tGaps=[],_avgMs=1000,_cntI=null;
function _onTick(){var now=Date.now(),g=now-_ltTs;_ltTs=now;if(g>180&&g<12000){_tGaps.push(g);if(_tGaps.length>20)_tGaps.shift();_avgMs=_tGaps.reduce(function(a,b){return a+b;},0)/_tGaps.length;}if(_sndOk())sndTick();}
function _startCnt(){if(_cntI)clearInterval(_cntI);var strip=document.getElementById('tick-countdown');if(strip)strip.style.display='flex';_cntI=setInterval(function(){var el=Date.now()-_ltTs,rem=Math.max(0,_avgMs-el),pct=(rem/_avgMs)*100;var col=pct>50?'#00c853':pct>20?'#f59e0b':'#ef4444';var b=document.getElementById('tcd-bar'),s=document.getElementById('tcd-secs'),p=document.getElementById('tcd-price-mini');if(b){b.style.width=pct+'%';b.style.background=col;}if(s){s.textContent=(rem/1000).toFixed(1)+'s';s.style.color=col;}if(p&&typeof fullHistory!=='undefined'&&fullHistory.length){var l=fullHistory[fullHistory.length-1];p.textContent=l.price.toFixed(typeof pipSize!=='undefined'?pipSize:4);p.style.color=l.diff>=0?'#00c853':'#ef4444';}},80);}

var _ofBan=null,_ofSt=false;
setInterval(function(){var g=Date.now()-_ltTs;if(g>9000&&!_ofSt){_ofSt=true;if(!_ofBan){_ofBan=document.createElement('div');_ofBan.style.cssText='position:fixed;top:0;left:0;right:0;z-index:99998;background:#d32f2f;color:#fff;text-align:center;font-size:11px;font-weight:900;padding:7px';_ofBan.textContent='📡 Feed offline — reconnecting…';document.body.appendChild(_ofBan);}toast('📡 No ticks received','offline',7000);}if(g<3000&&_ofSt){_ofSt=false;if(_ofBan){_ofBan.remove();_ofBan=null;}toast('✓ Feed restored','win',3000);}},2500);

var _oRA=typeof renderAll==='function'?renderAll:null;
renderAll=function(){if(_oRA)_oRA();setTimeout(function(){var sEl=document.querySelector('.sig'),bEl=document.querySelector('.sigbadge');if(!sEl)return;var sig=sEl.textContent.trim();if(!sig||sig==='—'||sig==='LOADING')return;var badge=bEl?bEl.textContent.trim():'';var conf=badge.indexOf('STRONG')>=0?'STRONG':badge.indexOf('MODERATE')>=0?'MODERATE':'WEAK';var aEl=document.querySelector('.bnav.on .bnav-txt');var type=aEl?aEl.textContent.trim():'—';var price=typeof fullHistory!=='undefined'&&fullHistory.length?fullHistory[fullHistory.length-1].price:null;_recSig(sig,conf,type,price);_onTick();},40);};

_updWR();_startCnt();
document.addEventListener('keydown',function(e){if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA')return;if(e.code==='Space'){e.preventDefault();logTrade('win');}if(e.code==='Backspace'){e.preventDefault();logTrade('loss');}if(e.key.toLowerCase()==='h')openSigDrawer();});
if(!localStorage.getItem('se_v2')){localStorage.setItem('se_v2','1');setTimeout(function(){toast('👋 Signals log automatically. 📋 Log tracks results. Space=WIN Backspace=LOSS','info',7000);},4000);}
